In [12]:
import numpy as np

In [14]:
nums_array = np.array([[1,2,3], [4,5,6]])
nums_array

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
nums_array[-1]


array([4, 5, 6])

In [16]:
nums_array.shape # 2 ряда 3 столбца 


(2, 3)

In [18]:
nums_array.ndim

2

In [21]:
second_array = np.array([[7,8,9], [10,11,12]])

In [22]:
 nums_array + second_array

array([[ 8, 10, 12],
       [14, 16, 18]])

In [23]:
nums_array[1,1]


np.int64(5)

In [34]:
np.concatenate((np.array([1,2,3]), np.array([4,5,6])))

array([1, 2, 3, 4, 5, 6])